# Generated by Django 3.1.12 on 2025-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('job', models.CharField(max_length=100, verbose_name='직업')),
                ('language', models.CharField(max_length=100, verbose_name='언어')),
                ('pay', models.IntegerField(verbose_name='급여')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원 목록',
                'db_table': 'employee',
                'ordering': ['-created_at'],
            },
        ),
    ]
